export const locations = [
  "DHA Phase 9 Prism - Block A",
  "DHA Phase 9 Prism - Block B",
  "DHA Phase 9 Prism - Block C",
  "DHA Phase 9 Prism - Block D",
  "DHA Phase 9 Prism - Block E",
  "DHA Phase 9 Prism - Block F",
  "DHA Phase 9 Prism - Block G",
  "DHA Phase 9 Prism - Block H",
  "DHA Phase 9 Prism - Block J",
  "DHA Phase 9 Prism - Block K",
  "DHA Phase 9 Prism - Block L",
  "DHA Phase 9 Prism - Block M",
  "DHA Phase 9 Prism - Block N",
  "DHA Phase 9 Prism - Block P",
  "DHA Phase 9 Prism - Block Q",
  "DHA Phase 9 Prism - Block R",
  "DHA Phase 9 Prism - Zone 1",
  "DHA Phase 9 Prism - Zone 2",
  "DHA Phase 9 Prism - Zone 3",
  "DHA Phase 9 Prism - Oval Complex",
  "DHA 9 Town - Block A",
  "DHA 9 Town - Block B",
  "DHA 9 Town - Block C",
  "DHA 9 Town - Block D",
  "DHA 9 Town - Block E",
  "DHA 9 Town - Commercial Area",
  "DHA 9 Town - CCA",
  "DHA Phase 8 - Block A (Park View)",
  "DHA Phase 8 - Block B (Park View)",
  "DHA Phase 8 - Block C (Park View)",
  "DHA Phase 8 - Block D (Park View)",
  "DHA Phase 8 - Block E (Park View)",
  "DHA Phase 8 - Block F (Park View)",
  "DHA Phase 8 - Block G (Park View)",
  "DHA Phase 8 - Block J (Park View)",
  "DHA Phase 8 - Block K (Park View)",
  "DHA Phase 8 - Block L (Air Avenue)",
  "DHA Phase 8 - Block M (Air Avenue)",
  "DHA Phase 8 - Block N (Air Avenue)",
  "DHA Phase 8 - Block P (Air Avenue)",
  "DHA Phase 8 - Block Q (Air Avenue)",
  "DHA Phase 8 - Block R (Air Avenue)",
  "DHA Phase 8 - Block S",
  "DHA Phase 8 - Block T",
  "DHA Phase 8 - Block U",
  "DHA Phase 8 - Block V",
  "DHA Phase 8 - Block W",
  "DHA Phase 8 - Block X",
  "DHA Phase 8 - Block Y",
  "DHA Phase 8 - Block Z",
  "DHA Phase 8 - Broadway Block A",
  "DHA Phase 8 - Broadway Block B",
  "DHA Phase 8 - Broadway Block C",
  "DHA Phase 8 - Broadway Block D",
  "DHA Phase 8 - CCA 1",
  "DHA Phase 8 - CCA 2",
  "DHA Phase 8 - CCA 3",
  "DHA Phase 8 - Block Z1",
  "DHA Phase 8 - Block Z2",
  "DHA Phase 8 - Block Z3",
  "DHA Phase 8 - Block Z4",
  "DHA Phase 8 - Block Z5",
  "DHA Phase 8 - Block Z6",
  "DHA Phase 7 - Block P",
  "DHA Phase 7 - Block Q",
  "DHA Phase 7 - Block R",
  "DHA Phase 7 - Block S",
  "DHA Phase 7 - Block T",
  "DHA Phase 7 - Block U",
  "DHA Phase 7 - Block V",
  "DHA Phase 7 - Block W",
  "DHA Phase 7 - Block X",
  "DHA Phase 7 - Block Y",
  "DHA Phase 7 - Block Z",
  "DHA Phase 7 - CCA 1",
  "DHA Phase 7 - CCA 2",
  "DHA Phase 7 - CCA 3",
  "DHA Phase 7 - CCA 4",
  "DHA Phase 7 - CCA 5",
  "DHA Phase 7 - CCA 6",
  "DHA Phase 7 - Block Z1",
  "DHA Phase 7 - Block Z2",
  "DHA Phase 6 - Block A",
  "DHA Phase 6 - Block B",
  "DHA Phase 6 - Block C",
  "DHA Phase 6 - Block D",
  "DHA Phase 6 - Block E",
  "DHA Phase 6 - Block F",
  "DHA Phase 6 - Block G",
  "DHA Phase 6 - Block H",
  "DHA Phase 6 - Block J",
  "DHA Phase 6 - Block K",
  "DHA Phase 6 - Block L",
  "DHA Phase 6 - Block M",
  "DHA Phase 6 - Block N",
  "DHA Phase 6 - Main Boulevard",
  "DHA Phase 6 - CCA Block",
  "DHA Phase 6 - CCA 1 Block",
  "DHA Phase 6 - CCA 2 Block",
  "DHA Phase 6 - CCA 3 Block",
  "DHA Phase 5 - CCA 2 Block",
  "DHA Phase 5 - CCA Block",
  "DHA Phase 5 - Block A",
  "DHA Phase 5 - Block B",
  "DHA Phase 5 - Block B Extension",
  "DHA Phase 5 - Block C",
  "DHA Phase 5 - Block D",
  "DHA Phase 5 - Block E",
  "DHA Phase 5 - Block F",
  "DHA Phase 5 - Block G",
  "DHA Phase 5 - Block H",
  "DHA Phase 5 - Block J",
  "DHA Phase 5 - Block K",
  "DHA Phase 5 - Block L",
  "DHA Phase 5 - Block M",
  "DHA Phase 5 - Block M Extension",
  "DHA Phase 4 - Block AA",
  "DHA Phase 4 - Block BB",
  "DHA Phase 4 - Block CC",
  "DHA Phase 4 - Block DD",
  "DHA Phase 4 - Block EE",
  "DHA Phase 4 - Block FF",
  "DHA Phase 4 - Block GG",
  "DHA Phase 4 - Block HH",
  "DHA Phase 4 - Block JJ",
  "DHA Phase 4 - Block KK",
  "DHA Phase 4 - Block LL",
  "DHA Phase 4 - CCA Block",
  "DHA Phase 3 - Block W",
  "DHA Phase 3 - Block X",
  "DHA Phase 3 - Block XX",
  "DHA Phase 3 - Block Y",
  "DHA Phase 3 - Block Z",
  "DHA Phase 2 - Block Q",
  "DHA Phase 2 - Block R",
  "DHA Phase 2 - Block S",
  "DHA Phase 2 - Block T",
  "DHA Phase 2 - Block U",
  "DHA Phase 2 - Block V",
  "DHA Phase 1 - Block A",
  "DHA Phase 1 - Block B",
  "DHA Phase 1 - Block C",
  "DHA Phase 1 - Block D",
  "DHA Phase 1 - Block E",
  "DHA Phase 1 - Block F",
  "DHA Phase 1 - Block G",
  "DHA Phase 1 - Block H",
  "DHA Phase 1 - Block J",
  "DHA Phase 1 - Block K",
  "DHA Phase 1 - Block L",
  "DHA Phase 1 - Block M",
  "DHA Phase 1 - Block N",
  "DHA Phase 1 - Block P",
  "DHA Phase 11 Halloki Gardens - Block A",
  "DHA Phase 11 Halloki Gardens - Block B",
  "DHA Phase 11 (Rahbar) - Block A",
  "DHA Phase 11 (Rahbar) - Block B",
  "DHA Phase 11 (Rahbar) - Block C",
  "DHA Phase 11 (Rahbar) - Block CCA",
  "DHA Phase 11 (Rahbar) - Block D",
  "DHA Phase 11 (Rahbar) - Block E",
  "DHA Phase 11 (Rahbar) - Block F",
  "DHA Phase 11 (Rahbar) - Block G",
  "DHA Phase 11 (Rahbar) - Block H",
  "DHA Phase 11 (Rahbar) - Block J",
  "DHA Phase 11 (Rahbar) - Block K",
  "DHA Phase 11 (Rahbar) - Block L",
  "DHA Phase 11 (Rahbar) - Block M",
  "DHA Phase 11 (Rahbar) - Block N",
  "DHA Phase 11 (Rahbar) - Block P",
  "DHA Phase 11 (Rahbar) - Block Q",
  "DHA Phase 11 (Rahbar) - Block R",
  "DHA Phase 11 (Rahbar) - Block S",
  "DHA Phase 11 (Rahbar) - Block CCA1",
  "DHA Phase 11 (Rahbar) - Block CCA2",
  "DHA Phase 11 (Rahbar) - Block CCA3",
  "DHA Phase 11 (Rahbar) - Block CCA4",
]
